### ISSUE TITLE
plot_data_overview equivalent

### ISSUE THREAD

**Issue by ddomingof** [bioFAM/mofapy2#34]
Is there an equivalent of the `plot_data_overview` [function](https://rdrr.io/github/bioFAM/MOFA2/man/plot_data_overview.html) in R implemented here?
Thank you!

**Comment by gtca** [comment]
Hey,

Not quite but I've just added a simple version of it into `mofax`, see [`plot_data_overview()`](https://github.com/bioFAM/mofax/blob/master/mofax/plot_data.py). Hope that helps!
